### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by tcoopman** [dylanirlbeck/tailwind-ppx#49]
I'm using `tailwind-ppx` with vscode and ocamllsp and I'm seeing regular cpu spikes of `tailwind-ppx`.
Not sure there is anything I can do to debug this for you.

I only have used the `[%tw]` a couple of times in the project (3 or so).

**Comment by dylanirlbeck** [comment]
Thanks for raising the issue! I've been meaning to do some benchmarks to test the performance, since I created this PPX rather fast and the algorithms used for validation are fairly naive. Is there a Github repo you can send me so I can test it out locally?

There might be something related to your configuration that could be causing the issue, so I'm very curious.

**Comment by tcoopman** [comment]
@dylanirlbeck I have a private repo  that I could share with you? Do you have any way of contacting you directly?

**Comment by dylanirlbeck** [comment]
My email is dylanirlbeck@gmail.com; feel free to reach out!

**Comment by dylanirlbeck** [comment]
@tcoopman Someone else reported performance issues on #72 --- I'm going to move the discussion about performance there. This upcoming week I'll spend some time investigating how I can improve the performance, since a few things come to mind.
