### ISSUE TITLE
focus:outline-none class name not found

### ISSUE THREAD

**Issue by sync** [dylanirlbeck/tailwind-ppx#59]
thanks agains for this. I am slowly backporting my app to this ppx and finding issues as we go.

https://tailwindcss.com/docs/pseudo-class-variants/#app

<img width="1680" alt="Screen Shot 2020-04-30 at 7 54 13 am" src="https://user-images.githubusercontent.com/21725/80650796-feff1680-8ab7-11ea-998a-58487f148fe0.png">

**Comment by sync** [comment]
same for `focus:shadow-outline`

**Comment by dylanirlbeck** [comment]
@sync Thanks for bringing up these issues! You're probably one of the first serious users, so I appreciate your patience as we progress towards a `v1.0`. I'll get a PR out for this bug asap --- hopefully I can also fix the ppx logic so no more class names get incorrectly ignored in the future.

**Comment by sync** [comment]
you don't need to rush take your time, none of these are a blocker, i'll use it when it's ready

**Comment by azkane** [comment]
I hope this is a good issue to aggregate classes that aren't working right now. I've found some:

- `.group` and `.group-hover:*`
The tailwind.css file doesn't explicitly generate a class for `.group` so it might get ignored (it was in postcss-bs-tailwind), it's written like this in the css: `.group:hover .group-hover\:bg-black`, the ppx reports it doesn't exist.

Using the `.group-hover` prefixed utility classes (e.g. `.group-hover:bg-white`) doesn't work either. For tailwind to generate those classes the `group-hover` variant must be enabled for some property, e.g 
```
variants: {
backgroundColor: [ 'group-hover'],`
}
```

![test](https://user-images.githubusercontent.com/3322582/80657602-aabd4d80-8a49-11ea-9ba4-16b961789e5b.png)

-  The [space between classes](https://tailwindcss.com/docs/space/#app)
The selector for those is written like e.g. `.space-x-0 > :not(template) ~ :not(template)` it might be tripping the parser because those aren't working either.

Thanks for your hard work!

**Comment by dylanirlbeck** [comment]
@azkane @sync Can you both double-check to see if you're still seeing this issue with `v0.6.3` https://www.npmjs.com/package/@dylanirlbeck/tailwind-ppx? I just released a new version that hopefully fixes these bugs.

**Comment by sync** [comment]
having a look in the next couple of hours

**Comment by tcoopman** [comment]
For me they seem all ok now :+1:

**Comment by sync** [comment]
All good I have successfully backported all my css to the ppx but it's quite slow i'll open another issue

**Comment by sync** [comment]
feel free to close this issue, amazing work thank you
