### ISSUE TITLE
Peformance Issues

### ISSUE THREAD

**Issue by sync** [dylanirlbeck/tailwind-ppx#72]
If i make a change to a className to with the ppx:

For example this component has 8 different class names.

### with the ppx
<img width="501" alt="with_ppx" src="https://user-images.githubusercontent.com/21725/80898382-18b58d80-8d46-11ea-8f38-1443950dfe8c.png">

### without the ppx
<img width="453" alt="witout_ppx" src="https://user-images.githubusercontent.com/21725/80898383-1fdc9b80-8d46-11ea-9b00-b4b201ef2f7b.png">

Related to #49

**Comment by dylanirlbeck** [comment]
Hi @sync . Thanks for bringing up this issue --- I'll need to dive deeper into benchmarking this week since other users have also been experiencing performance issues. I'm confident there are some hacks I can do to speed up the performance, so stay tuned.

**Comment by sync** [comment]
Thank you and once more no pressure at all, thinks are looking good already and I am certain you'll be able to figure it out :-)

**Comment by tcoopman** [comment]
I noticed similar performance issues so let me know if I can test anything.
I think a good idea would be to have some benchmarks added somewhere?
Maybe just a huge component with lots of classes could already be enough?

**Comment by tatchi** [comment]
I've tried to measure some of the function's execution time and it turns out that the parsing of the css file is the one taking most of the time. 

This function is run during every compilation. Since the result of this function should always be the same for the same css file content, it would probably be nice to somehow cache the result across compilation.

I've tried to store the result in a file so the subsequent compilations can avoid the parsing step and just reading the file. It already significantly improve the performance but I'm wondering if we can still make it better and avoid reading from a file? Is there a way to persist things in memory between compilations?


Note that I tried with a small example so results might be different with a bigger project.

**Comment by dylanirlbeck** [comment]
@tatchi This was my idea exactly --- I'm planning on adding a cache that hashes the contents of the tailwind.css file, and only parse again only if the hash differs. I'd welcome anyone who has other ideas (I have a few), but this is an obvious first step towards improving performance!

**Comment by tatchi** [comment]
@dylanirlbeck Thanks. Were you thinking about storing the result of the parsing in a file or do you have a better solution?

**Comment by dylanirlbeck** [comment]
So @tatchi my thought was that the actual result of the parser is not super important - what's more important are the acceptable class names (that you get after parsing). For the cache, I was thinking about doing something along the lines of a JSON object with the following schema

```json
{
   "tailwindCssHash": "...",
   "acceptableClassNames": [
    ... (list of acceptable names)
   ]
}
```

Upon re-building the project we just re-hash the tailwind.css file and compare it to what's in the `.tailwind_ppx_cache` file. What do you think?

**Comment by tcoopman** [comment]
I guess storing something in a file is a good approach. To keep something in memory you would need an other process that stays up between builds, but I don't think there is support from the build files for this, so personally I wouldn't take this approach.

2 possible performance improvements that could be added to the file approach (later?):

1. Maybe it's a good idea to measure the cost of hashing `tailwind.css` as well? If that's too costly an approach could be to compare the last edited time of the file and only if it's different calculate the hash again.

2. I'm guessing that you then read the list of acceptableClassNames into a set or something with fast access? Maybe it's also worth storing the output of that set instead of the list to reduce the time rebuilding the set? And other option would be to store the acceptableClassNames in alphabetical order and read them into an array and use a binary search on that array.

Both methods might not be worth the extra effort though.

**Comment by tcoopman** [comment]
For 2 the Marshal module might be useful: https://caml.inria.fr/pub/docs/manual-ocaml/libref/Marshal.html this would allow you to store and read the Set directly which is probably a good deal faster than parsing the json and creating a set out of it.

**Comment by tatchi** [comment]
> So @tatchi my thought was that the actual result of the parser is not super important - what's more important are the acceptable class names (that you get after parsing). For the cache, I was thinking about doing something along the lines of a JSON object with the following schema
> 
> ```
> {
>    "tailwindCssHash": "...",
>    "acceptableClassNames": [
>     ... (list of acceptable names)
>    ]
> }
> ```
> 
> Upon re-building the project we just re-hash the tailwind.css file and compare it to what's in the `.tailwind_ppx_cache` file. What do you think?

Indeed, I also thought about storing the acceptable classNames since at the end that's what we need. I guess it should be also smaller which is good. I'll make this change and add the hashing logic to my branch :)

**Comment by tatchi** [comment]
> For 2 the Marshal module might be useful: https://caml.inria.fr/pub/docs/manual-ocaml/libref/Marshal.html this would allow you to store and read the Set directly which is probably a good deal faster than parsing the json and creating a set out of it.

Indeed that's what I've been using. It's not safe but I guess in this scenario it should be fine :)

**Comment by dylanirlbeck** [comment]
Wow that Marshal module looks like exactly what we need for this! Great find 😄 

@tatchi I don't want to duplicate any work you might be doing with hashing/caching --- are you planning on opening a PR?

**Comment by tatchi** [comment]
@dylanirlbeck Yes, I would be happy to open a PR if it's ok for you. I still need to include some changes following our discussion and it should be good.

**Comment by dylanirlbeck** [comment]
@sync @tcoopman Can you both upgrade your `tailwind-ppx` version to 0.7.0? I just merged in the PR for caching so hopefully you all see major improvements!! (let me know if you don't)

**Comment by tcoopman** [comment]
Looks a lot better. I saw a spike the first time, but after the cache was created it seems a lot better. This was a quick test so far, if I see anything else I'll let you know.

Great work @tatchi!

Maybe it would be good to add this to the readme so people know they should probably put the `.tailwind_ppx_cache` in `.gitignore` and explain why it's there.

**Comment by tcoopman** [comment]
I'm on Linux btw, maybe it would be good to test this on all platforms.

**Comment by dylanirlbeck** [comment]
@tcoopman Docs are already added: https://github.com/dylanirlbeck/tailwind-ppx#ignore-tailwind_ppx_cache-in-your-version-control. Can you see if there's anything to add?

**Comment by dylanirlbeck** [comment]
Going to close this out for now. Feel free to re-open if performance issues come up again! I'll hopefully be adding benchmarking in the near future as well.
